# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58e8615bfe79ef8666d185170c2bf8a5271400fe538e600d2bac9bb002fffa88a089464ff8524e2ca4e6d0977ded0f1781c050bddfe11d9d3ccfb18211719249

test:
  secret_key_base: 70e404aa99ecff19851bd3bfe4764420a3f91236ab6d5a85f2c835ee696ac5526d6a1b32b0614abf103565c35a1be5eae9be3b425eda3e0cd51ade4a36156ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
